sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
  - 1.31.0 # minimum supported version
script:
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo generate-lockfile -Z minimal-versions;
    else
      cargo generate-lockfile;
    fi
  - cargo build --verbose --locked
  - cargo test --verbose --locked
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo bench;
    fi
