sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
  - 1.13.0 # currently oldest supported version
script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
        cargo bench;
    fi
