sudo: false
language: rust
cache: cargo
rust:
  - nightly
  - beta
  - stable
  - 1.31.0 # minimum supported version
script:
  - cargo build --verbose
  - cargo test --verbose
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then
      cargo bench;
    fi
